name: Deploy Project

on:
  workflow_run:
    workflows: ["Test Project"]
    branches: [main]
    types:
      - completed

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Dummy deploy
      run: echo "Deployed!"
