name: Test Project Again

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dummy command
      run: touch foo 
    - name: Run our gradle task
      run: ./gradlew useCurlOnGoogle --info
