name: Test Project

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dummy command
      run: touch foo 
    - name: First one fails
      run: |
        false
        true
    - name: Seconnd one fails
      run: |
        true
        false
