name: Test Project

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dummy command
      run: touch foo 
#    - name: First one fails # this one does fail and causes the next run to be skipped!
#      run: |
#        false
#        true
    - name: Seconnd one fails
      run: |
        true
        false
